import { BackgroundBeamsWithCollision } from "@/components/ui/background-beams-with-collision";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${jetbrainsMono.variable} antialiased`}
      >
        <BackgroundBeamsWithCollision className="min-h-screen w-full overflow-visible">
          {children}
        </BackgroundBeamsWithCollision>
      </body>
    </html>
  );
}
